repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0  # Use the latest stable tag
    hooks:
      - id: check-added-large-files
        args: ['—-maxkb=1000']
        name: Check for added large files
      - id: check-case-conflict
        name: Check files for case conflicts on case-insensitive filesystems
      - id: check-executables-have-shebangs
        name: Check that executables have shebangs
      - id: check-merge-conflict
        name: Check for files that contain merge conflict strings
      - id: check-shebang-scripts-are-executable
        name: Check that shebang scripts are executable
      - id: check-toml
        name: Check valid TOML syntax
      - id: check-xml
        name: Check valid XML syntax
      - id: end-of-file-fixer
        name: Check for newline at end of file
        exclude: '^LICENSE$'
      - id: no-commit-to-branch
        name: Check to not commit to main
      - id: trailing-whitespace
        name: Check for trailing whitespaces
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v20.1.0
    hooks:
      - id: clang-format
        name: Run clang-format (C/C++ formatter)
        types_or: [c, c++]
  - repo: https://github.com/pamoller/xmlformatter
    rev: v0.2.8
    hooks:
      - id: xml-formatter
        name: Run xml-formatter
        args: [--indent, "2", --indent-char, " ", --selfclose, --overwrite, --eof-newline]
