name: mirco_ci

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  schedule:
    - cron: '00 6 * * *'
  workflow_dispatch:

jobs:
  code-check:
    name: code_check
    runs-on: ubuntu-latest
    env:
      CTEST_FAIL_ON_WARNING: "1"
    steps:
      - uses: actions/checkout@v4
      - name: Check code.
        run: |
          source create-mirco-python-venv.sh
          find src/ tests/ -iname *.h -o -iname *.c -o -iname *.cpp -o -iname *.hpp | xargs clang-format -style=file -i -fallback-style=none
          git diff > clang_format.patch
          if [ -s clang_format.patch ]
          then
            echo "Formatting incorrect. Run 'find src/ tests/ -iname *.h -o -iname *.c -o -iname *.cpp -o -iname *.hpp | xargs clang-format -style=file -i -fallback-style=none' in your local source directory and push it."
            exit 1
          fi

  mirco-test:
    name: mirco_test_full
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/philipoesterlepekrun/mirco-kokkos-dependencies:latest

    env:
      CTEST_FAIL_ON_WARNING: "1"

    steps:
      - name: Checkout code with submodules
        uses: actions/checkout@v5
        with:
          submodules: recursive
          path: mirco-src
          fetch-depth: 0  # Necessary for full git history and tags

      - name: Build and test
        run: |
          mkdir mirco-build
          cd mirco-build
          cmake --preset=docker_container ../mirco-src/
          ninja -j 12
          ctest --output-on-failure

  mirco-test_kokkos:
    name: mirco_test_full_kokkos
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/philipoesterlepekrun/mirco-kokkos-dependencies:latest

    env:
      CTEST_FAIL_ON_WARNING: "1"

    steps:
      - name: Checkout code with submodules
        uses: actions/checkout@v5
        with:
          submodules: recursive
          path: mirco-src
          fetch-depth: 0  # Necessary for full git history and tags

      - name: Build and test
        run: |
          mkdir mirco-build
          cd mirco-build
          cmake --preset=docker_container_kokkos ../mirco-src/
          ninja -j 12
          ctest --output-on-failure
