on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  schedule:
    - cron: '00 6 * * *'
  workflow_dispatch:
    type: choice

jobs:
  mirco-test:
    name: mirco_test_full
    runs-on: self-hosted
    env:
      CTEST_FAIL_ON_WARNING: "1"
      TEST_DIRECTORY: "/home_local/github-runner/actions-runner/_work/MIRCO"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Delete old build files.
        run: rm -rf ../mirco_build/
      - name: Clear ccache cache.
        run: 'if [ -x "$(command -v ccache)" ]; then ccache -C -z; echo "ccache cache cleared"; fi'
      - name: Run build and ctest
        run: 'ctest -S ${{env.TEST_DIRECTORY}}/MIRCO/tests/testconfig/test_release.cmake -VV || tee ../buildtest.log'
